project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true



files: [
  {
    "source": "/PlayNext/Localization/en_US.xaml",
    "dest": "Playnite.PlayNext/PlayNext/Localization/en_US.xaml",
    "translation": "/PlayNext/Localization/%locale_with_underscore%.xaml",
    "escape_quotes": 3,
    "escape_special_characters": 0,
    "update_option": "update_as_unapproved"
  }
]
